#MQTT Links Advertise Enable ( "no" or "yes")
LINK_ENABLE=no
#MQTT Links Advertise service to start on boot ( "no" or "yes")
LINK_BOOT=no
#MQTT Links Advertise service crontab start ( "no" or "yes")
LINK_CRON=no
#MQTT Links Advertise service crontab. Default every hour
LINK_CRONTAB=0 * * * *
#MQTT Links Advertise service Topic
LINK_TOPIC=links
#MQTT Links Advertise service Retain
LINK_RETAIN=1
#MQTT Link Advertise service QOS
LINK_QOS=0

#MQTT Global Information Advertise Enable ( "no" or "yes")
INFO_GLOBAL_ENABLE=no
#MQTT Global Information Advertise service to start on boot ( "no" or "yes")
INFO_GLOBAL_BOOT=no
#MQTT Global Information Advertise service crontab start ( "no" or "yes")
INFO_GLOBAL_CRON=no
#MQTT Global Information Advertise service crontab. Default every hour
INFO_GLOBAL_CRONTAB=0 * * * *
#MQTT Global Information Advertise service Topic
INFO_GLOBAL_TOPIC=info_global
#MQTT Global Information Advertise service Retain
INFO_GLOBAL_RETAIN=1
#MQTT Global Information Advertise service QOS
INFO_GLOBAL_QOS=0

#MQTT Camera Setting Advertise Enable ( "no" or "yes")
CAMERA_SETTING_ENABLE=no
#MQTT Camera Setting Advertise service to start on boot ( "no" or "yes")
CAMERA_SETTING_BOOT=no
#MQTT Camera Setting Advertise service crontab start ( "no" or "yes")
CAMERA_SETTING_CRON=no
#MQTT Camera Setting Advertise service crontab. Default every hour
CAMERA_SETTING_CRONTAB=0 * * * *
#MQTT Camera Setting Advertise service Topic
CAMERA_SETTING_TOPIC=camera_setting
#MQTT Camera Setting Advertise service Retain
CAMERA_SETTING_RETAIN=0
#MQTT Camera Setting Advertise service QOS
CAMERA_SETTING_QOS=0

#MQTT Telemetry Advertise Enable ( "no" or "yes")
TELEMETRY_ENABLE=no
#MQTT Telemetry Advertise service to start on boot ( "no" or "yes")
TELEMETRY_BOOT=no
#MQTT Telemetry Advertise service crontab start ( "no" or "yes")
TELEMETRY_CRON=no
#MQTT Telemetry Advertise service crontab. Default every 10 minute
TELEMETRY_CRONTAB=*/10 * * * *
#MQTT Telemetry Advertise service crontab. Default every 10 minute
TELEMETRY_TOPIC=telemetry
#MQTT Telemetry Advertise service Retain
TELEMETRY_RETAIN=1
#MQTT Telemetry Advertise service QOS
TELEMETRY_QOS=0

#Home Assistant Enable ( "no" or "yes")
HOMEASSISTANT_ENABLE=no
#Home Assistant MQTT discovery advertise service to start on boot ( "no" or "yes")
HOMEASSISTANT_BOOT=no
#Home Assistant MQTT discovery crontab start ( "no" or "yes")
HOMEASSISTANT_CRON=no
#Home Assistant MQTT discovery crontab. Default every hour
HOMEASSISTANT_CRONTAB=0 * * * *

# Don't use double quote "
#Home Assistant discovery topic, should be "homeassistant"
HOMEASSISTANT_MQTT_PREFIX=homeassistant

# NOTE: the Home Assistant device name and identifiers are unique per camera and
# live in identity.conf.
# Device Manufacturer - used by Home Assistant
HOMEASSISTANT_MANUFACTURER=YI
# Device Model  - It used by Homeassistant
HOMEASSISTANT_MODEL=YI Hack
#MHome Assistant discovery Retain
HOMEASSISTANT_RETAIN=1
#MHome Assistant discovery QOS
HOMEASSISTANT_QOS=1
