SWITCH_ON=yes
SENSITIVITY=low
LED=yes
ROTATE=no
IR=yes
MIC=yes
CRUISE=no
MOTION_TRACKING=no
MOTION_DETECTION=yes
SAVE_VIDEO_ON_MOTION=yes
SOUND_DETECTION=no
SOUND_SENSITIVITY=80
BABY_CRYING_DETECT=no
AI_HUMAN_DETECTION=no
AI_VEHICLE_DETECTION=no
AI_ANIMAL_DETECTION=no
FACE_DETECTION=no
