#!/usr/bin/env python3
# simulate_boot.py - yi-hack-v6
#
# Static boot emulation: walks the v6 boot chain (CAMERA_FIRMWARE_DESIGN.md section 4.4),
# logs each action, and verifies that every referenced file exists, classifying it as:
#   [flash]   - our file in /home/yi-hack (must exist in the repo)        -> ERROR if missing
#   [stock]   - Xiaomi binary/script baked into flash from stock firmware -> info (ref stock_firmware)
#   [payload] - lives in extra/ on SD/CIFS, deployed separately           -> info
#   [build]   - artifact produced at build time (e.g. ipc_multiplex.so)   -> info
#   [todo]    - planned but not built yet (e.g. rescue UI)                -> warn
#
# Run from repo root:  python3 scripts/simulate_boot.py   -> writes simulated_boot.log

import os, sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC = os.path.join(REPO, "src/static/static")
STOCK  = os.path.join(REPO, "stock_firmware/home_extracted")

log_lines = []
errors = 0
warns = 0

def out(s=""):
    log_lines.append(s)

def repo_path(runtime):
    """Map a runtime path to its source path in the repo, or None if not flash-resident here."""
    if runtime.startswith("/home/yi-hack/"):
        return os.path.join(STATIC, "home/yi-hack", runtime[len("/home/yi-hack/"):])
    if runtime.startswith("/etc/"):
        return os.path.join(STATIC, "rootfs/etc", runtime[len("/etc/"):])
    return None

def check(runtime, kind="flash", note=""):
    """Check a referenced path. kind in flash/stock/payload/build/todo."""
    global errors, warns
    tag = {"flash":"[flash]","stock":"[stock]","payload":"[payload]","build":"[build]","todo":"[todo]"}[kind]
    suffix = f"  {note}" if note else ""
    if kind == "flash":
        p = repo_path(runtime)
        if p and os.path.exists(p):
            out(f"    OK   {tag} {runtime}{suffix}")
        else:
            out(f"    MISS {tag} {runtime}  <-- MISSING IN REPO{suffix}")
            errors += 1
    elif kind == "stock":
        # reference existence in the extracted stock firmware (home + rootfs) for reassurance
        ref = None
        if runtime.startswith("/home/"):
            ref = os.path.join(STOCK, runtime[len("/home/"):])
        elif runtime.startswith("/etc/"):
            ref = os.path.join(REPO, "stock_firmware/rootfs_extracted/etc", runtime[len("/etc/"):])
        present = (ref and os.path.exists(ref))
        out(f"    --   {tag} {runtime}  (stock, baked in flash{'; ref present' if present else ''}){suffix}")
    elif kind == "payload":
        out(f"    --   {tag} {runtime}  (on SD/CIFS, deployed separately){suffix}")
    elif kind == "build":
        out(f"    --   {tag} {runtime}  (produced at build time){suffix}")
    elif kind == "todo":
        out(f"    !!   {tag} {runtime}  (not built yet){suffix}")
        warns += 1

def stage(title):
    out("")
    out(f">>> {title}")

# ---------------------------------------------------------------------------
out("=" * 78)
out(" yi-hack-v6 - SIMULATED BOOT (static file-existence trace)")
out(" Generated by scripts/simulate_boot.py - see CAMERA_FIRMWARE_DESIGN.md section 4.4")
out("=" * 78)

stage("kernel -> busybox init -> inittab ::sysinit -> rcS -> /etc/init.d/S[0-9][0-9]* in order")
check("/etc/inittab", "stock", "::sysinit:/etc/init.d/rcS")
check("/etc/init.d/rcS", "stock", "for initscript in /etc/init.d/S[0-9][0-9]*; do $initscript")
check("/etc/init.d/S00devs", "stock", "base device nodes")
check("/etc/init.d/S01udev", "flash", "yi-hack overlay (replaces stock)")
check("/etc/init.d/S20yi-hack", "flash", "yi-hack overlay (new)")

stage("S01udev: devpts, udev, mount FLASH /home, then system_init + base/init")
out("    action: mkdir /dev/pts; mount devpts; udevd; udevadm trigger")
out("    action: mount -t jffs2 /dev/mtdblock5 /home   (FLASH mounted)")
check("/home/yi-hack/base/script/system_init.sh", "flash")
check("/home/base/init.sh", "stock")

stage("system_init.sh: first-boot extraction + cloudAPI hooks + sed-patches")
out("    action: detect flash prefix (/home|/usr); [first boot] extract *.7z")
check("/home/yi-hack/base/script/cloudAPI", "flash", "-> copied to /home/app")
check("/home/yi-hack/base/script/cloudAPI_fake", "flash", "-> copied to /home/app")
check("/home/yi-hack/base/script/default.script", "flash", "udhcpc hook")
check("/home/yi-hack/base/script/wifidhcp.sh", "flash", "dhcp hook")
out("    action: mkdir config/crontabs, config/dropbear")
out("    action: sed-patch /home/app/init.sh (comment cloud daemons, swappiness 0->60)")
out("    action: sed-patch /home/base/init.sh (comment hanging rtc command)")

stage("base/init.sh [stock]: modules, /tmp tmpfs, mount SD, OTA check, app/init.sh")
out("    action: insmod exfat/hi_rtc; sysctl; mount tmpfs /tmp (16MB); mkdir /tmp/sd")
out("    action: checkdisk; mount /dev/mmcblk0p1 /tmp/sd   (SD if present)")
out("    cond:   [home_y20m + version mismatch] -> stock signed OTA (extpkg) -> reboot")
check("/home/app/init.sh", "stock")

stage("app/init.sh [stock, sed-patched]: WiFi up, HW modules; cloud daemons commented")
out("    action: insmod WiFi driver (bcmdhd|mt7601); ifconfig wlan0 up; resolv.conf")
out("    action: log_server &; load3518e (ISP); hi_cipher.ko; watchdog.ko")
out("    => WiFi UP, hardware modules loaded")

stage("S20yi-hack: mount_cifs -> build_view -> dispatcher | minimal boot")
out("    action: export LD_LIBRARY_PATH / PATH")
check("/home/yi-hack/base/script/mount_cifs.sh", "flash")
out("      cond: [cifs.ENABLED=yes] insmod md4/hmac/cifs; mount //HOST/SHARE /tmp/cifs (retry)")
check("/home/app/localko/cifs.ko", "stock", "+ md4.ko + hmac.ko")
check("/home/yi-hack/base/script/get_config.sh", "flash", "sourced by mount_cifs/build_view/dispatcher")
check("/home/yi-hack/config/cifs.conf", "flash")
check("/home/yi-hack/base/script/build_view.sh", "flash")
check("/home/yi-hack/config/output.conf", "flash")
out("      action: extra -> CIFS|SD|none ; www -> extra/www|base/www-min ; output/* per matrix")
check("/home/yi-hack/extra/www", "payload", "full UI (if payload present)")
check("/home/yi-hack/base/www-min/index.html", "flash", "rescue UI (section 5.9)")
for c in ("status.sh","get.sh","save.sh","cifstest.sh","reboot.sh","rescue_lib.sh"):
    check(f"/home/yi-hack/base/www-min/cgi-bin/{c}", "flash", "rescue CGI")

stage("[build_view exit 0] DISPATCHER system.sh")
check("/home/yi-hack/base/script/system.sh", "flash")
out("    reads: /home/yi-hack/config/*.conf via get_config")
for c in ("system.conf","camera.conf","mqttv4.conf","output.conf","cifs.conf","hostname"):
    check(f"/home/yi-hack/config/{c}", "flash")
out("    calls (flash helpers):")
for h in ("check_conf.sh","configure_wifi.sh","wd_rtsp.sh","conf2mqtt.sh","ptz_presets.sh",
          "clean_records.sh","ftppush.sh","check_update.sh"):
    check(f"/home/yi-hack/base/script/{h}", "flash")
check("/home/yi-hack/base/script/mqtt_advertise/startup.sh", "flash", "[MQTT] advertise")
check("/home/yi-hack/base/lib/ipc_multiplex.so", "build", "LD_PRELOAD for dispatch")
out("    launches (stock cloud daemons, per DISABLE_CLOUD):")
for b in ("dispatch","rmm","cloud","mp4record","p2p_tnp","oss","watch_process"):
    check(f"/home/app/{b}", "stock")
out("    launches (payload services, per config):")
for b in ("rRTSPServer","h264grabber","ipc_cmd","onvif_simple_server","onvif_notify_server","framefinder","mqttv4"):
    check(f"/home/yi-hack/extra/bin/{b}", "payload")
check("/home/yi-hack/extra/version", "payload", "ONVIF firmware_ver")
out("    serves: httpd -h /home/yi-hack/www   (single web UI path)")

stage("[build_view exit 1] MINIMAL BOOT (no payload)")
out("    action: httpd -h /home/yi-hack/www (rescue) & ; telnetd &")
out("    cond:   [config/privacy != on] launch stock Xiaomi cloud daemons + ftpd")
out("    => camera usable via Yi app; always reconfigurable via rescue UI + telnet")

# ---------------------------------------------------------------------------
out("")
out("=" * 78)
out(f" RESULT: {errors} missing flash file(s), {warns} not-built-yet warning(s)")
if errors == 0:
    out(" All flash-resident (our) files referenced by the boot chain exist.")
out(" Notes: [stock]=Xiaomi (baked in flash), [payload]=extra on SD/CIFS,")
out("        [build]=produced at build, [todo]=planned (section 5.9).")
out("=" * 78)

with open(os.path.join(REPO, "simulated_boot.log"), "w") as f:
    f.write("\n".join(log_lines) + "\n")
print("\n".join(log_lines))
sys.exit(1 if errors else 0)
